---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore,archive]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title: Brainhack Global Ghent 2018
keywords: brainhack, hackaton, neuroscience, ghent, cognitive science, fMRI, modelling, simulations, open science
description: Participate in open, reproducible neuroscience related projects to Brainhack Ghent 2018! Brainhack Ghent is a part of Brainhack Global  event.
#source_link:
#favicon: favicon.png?
url: https://brainhackghent.github.io
#touch_icon:
#google_analytics_key: UA-104097157-1
twitter_description: The registration for the  Brainhack Ghent 2018 is now open!
#

### template colors, used site-wide via css ###

colors:

  aongreen: '#1C7439'
  ugentblue: '#1E64C8'
  ugentyellow: ' #FFD200'
  white:     '#eee'
### flat  design colors from https://www.materialui.co/flatuicolors
  turquoise: '#1abc9c'
  emerald   : '#2ecc71'
  peteriver : '#3498db'
  amethyst  : '#9b59b6'
  wetasphalt : '#34495e'
  red: '#F44336'
  pink: '#ff80ab'
  cyan: '#1ba1e2'
  cobalt: '#0050ef'
  blueibro: '#051d9b'
  blueblue: '#2942C'
  azul: '#1760E4'  
### choose matarial design colors from http://materialuicolors.co/


kramdown:
  auto_ids:  false

sass:
  sass_dir: stylesheets/_sass/

theme: jekyll-theme-slate
